-- =====================================================================================
-- PERBAIKAN SKEMA PENTING (JALANKAN INI DI EDITOR SQL SUPABASE ANDA)
-- =====================================================================================
-- Tujuan:
-- 1. Memperbaiki relasi antara tabel 'orders' dan 'profiles'
-- 2. Menambahkan kebijakan agar admin dapat membaca semua profil pelanggan
-- 3. Menjamin RLS & Supabase Realtime dikonfigurasi dengan benar
-- =====================================================================================


-- PERINTAH 1: Pastikan RLS diaktifkan pada tabel profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- PERINTAH 2: Tambahkan kebijakan agar pengguna biasa hanya bisa akses profilnya sendiri
CREATE POLICY IF NOT EXISTS "Allow users to access their own profile"
ON public.profiles
FOR ALL
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- PERINTAH 3: Tambahkan kebijakan agar admin dapat membaca semua profil
CREATE POLICY IF NOT EXISTS "Allow admin to read all profiles"
ON public.profiles
FOR SELECT
USING (is_admin());


-- =====================================================================================
-- PERBAIKAN RELASI ORDERS → PROFILES
-- =====================================================================================

-- 1. Hapus foreign key lama (jika masih menunjuk ke auth.users)
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_user_id_fkey;

-- 2. Tambahkan foreign key baru ke public.profiles(id)
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey 
FOREIGN KEY (user_id) REFERENCES public.profiles(id);


-- =====================================================================================
-- SKEMA LENGKAP UNTUK REFERENSI
-- =====================================================================================

-- Tabel orders (jika belum ada)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    order_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_details JSONB NOT NULL,
    shipping_address JSONB NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Proses Admin'::text NOT NULL,
    shipping_receipt TEXT,
    notes TEXT
);

-- Aktifkan RLS
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Kebijakan untuk pengguna biasa
CREATE POLICY IF NOT EXISTS "Allow users to view their own orders"
ON public.orders FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY IF NOT EXISTS "Allow users to create their own orders"
ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);


-- =====================================================================================
-- INFRASTRUKTUR ADMIN
-- =====================================================================================

CREATE TABLE IF NOT EXISTS public.admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id)
);

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Kebijakan Admin untuk 'orders'
CREATE POLICY IF NOT EXISTS "Allow admin full access"
ON public.orders
FOR ALL
USING (is_admin())
WITH CHECK (is_admin());


-- =====================================================================================
-- SUPABASE REALTIME SETUP
-- =====================================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
  END IF;
END $$;
