-- =====================================================================================
-- PERBAIKAN SKEMA PENTING (JALANKAN INI DI EDITOR SQL SUPABASE ANDA)
-- =====================================================================================
-- Perintah berikut memperbaiki relasi antara tabel 'orders' dan 'profiles'.
-- Ini akan menyelesaikan error "Could not find a relationship" di halaman admin.

-- 1. Hapus foreign key lama (yang menunjuk ke auth.users)
-- CATATAN: Nama constraint bisa berbeda di database Anda.
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_user_id_fkey;

-- 2. Tambahkan foreign key baru yang menunjuk ke public.profiles(id)
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey 
FOREIGN KEY (user_id) REFERENCES public.profiles(id);

-- =====================================================================================
-- SKEMA LENGKAP UNTUK REFERENSI
-- =====================================================================================

-- Membuat tabel 'orders' untuk menyimpan data pesanan.
-- Sudah menggunakan foreign key ke profiles(id), menambahkan kolom 'notes',
-- dan default status 'Proses Admin'.
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    order_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_details JSONB NOT NULL,
    shipping_address JSONB NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Proses Admin'::text NOT NULL,
    shipping_receipt TEXT,
    notes TEXT
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan RLS untuk pengguna biasa
CREATE POLICY "Allow users to view their own orders"
ON public.orders
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Allow users to create their own orders"
ON public.orders
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 4. Infrastruktur & kebijakan untuk admin
CREATE TABLE IF NOT EXISTS public.admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id)
);

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Hapus kebijakan "FOR ALL" yang lama dan ambigu
DROP POLICY IF EXISTS "Allow admin full access" ON public.orders;

-- Kebijakan baru yang lebih eksplisit untuk admin
CREATE POLICY "Allow admin to view all orders"
ON public.orders
FOR SELECT USING (is_admin());

CREATE POLICY "Allow admin to update orders"
ON public.orders
FOR UPDATE USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "Allow admin to delete orders"
ON public.orders
FOR DELETE USING (is_admin());

-- 5. Supabase Realtime setup
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
  END IF;
END $$;

-- =====================================================================================
-- SKEMA BARU: TABEL PRODUK
-- =====================================================================================

-- CATATAN PENTING:
-- Setelah tabel 'products' dibuat, Anda perlu mengisinya dengan data awal.
-- Buka file 'supabase_seed.sql', salin kontennya, dan jalankan di SQL Editor
-- untuk menambahkan produk contoh ke database Anda.

-- 1. Membuat tabel 'products' untuk menyimpan data produk
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    price NUMERIC NOT NULL,
    char TEXT,
    description TEXT,
    image_url TEXT
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan RLS untuk Produk
-- a. Izinkan semua pengguna (termasuk anonim) untuk melihat produk
CREATE POLICY "Allow public read access to products"
ON public.products
FOR SELECT
USING (true);

-- b. Izinkan admin untuk melakukan semua operasi (SELECT, INSERT, UPDATE, DELETE)
CREATE POLICY "Allow admin full access to products"
ON public.products
FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- 4. Membuat Supabase Storage Bucket untuk gambar produk
-- Pastikan bucket 'product-images' dibuat di dashboard Supabase Anda
-- dengan akses publik.
-- (Ini adalah komentar, tindakan sebenarnya dilakukan di UI Supabase)
