-- =====================================================================================
-- SKRIP SEED UNTUK TABEL 'products'
-- =====================================================================================
-- Skrip ini mengisi tabel 'products' dengan data produk awal
-- yang sebelumnya disimpan di dalam file 'js/app.js'.
--
-- Cara penggunaan:
-- 1. Buka dashboard proyek Supabase Anda.
-- 2. Arahkan ke 'SQL Editor'.
-- 3. Salin dan tempel seluruh konten file ini ke dalam editor.
-- 4. Klik 'Run'.
--
-- Ini akan memasukkan semua produk contoh ke dalam database Anda.

-- Kosongkan data yang ada untuk mencegah duplikasi jika skrip dijalankan beberapa kali
TRUNCATE TABLE public.products RESTART IDENTITY;

-- Masukkan data baru
INSERT INTO public.products (name, category, price, "characteristics", description, image_url) VALUES
('Benih Cabai Carolina', 'benih', 12000, '1 pack berisi ±12 biji <br> - Benih Unggul <br> - Tingkat Pedas: Sangat Tinggi (±2.200.000 SHU) <br> - Perawatan: Sedang <br> - Masa Panen: ±90 hari', 'Benih Cabai Carolina Reaper, hasil persilangan antara Habanero dan Ghost Pepper, dikenal sebagai salah satu cabai terpedas di dunia dengan tingkat kepedasan mencapai sekitar 2,2 juta Scoville Heat Units (SHU). Cabai ini memiliki bentuk keriput dan ekor khas pada ujung buahnya. Cocok untuk para pecinta pedas ekstrem dan penggemar koleksi cabai langka. Tumbuh optimal di daerah tropis dengan sinar matahari penuh, penyiraman rutin, serta pemupukan organik seimbang untuk hasil terbaik.', 'img/general/Cabai Carolina.png'),
('Benih Cabai Fatalii', 'benih', 12000, '1 pack berisi ±12 biji <br> - Rasa Pedas & Sitrus <br> - Tingkat Pedas: 125.000–400.000 SHU <br> - Asal: Afrika Tengah <br> - Panen: ±80 hari', 'Benih Cabai Fatalii berasal dari Afrika Tengah dan terkenal dengan rasa pedas tajam berpadu aroma sitrus yang segar. Buahnya berwarna kuning cerah ketika matang, cocok untuk saus pedas, sambal fermentasi, atau olahan cabai segar. Varietas ini mudah tumbuh di iklim tropis, cepat berbuah, dan memiliki produktivitas tinggi. Cocok untuk ditanam di pot maupun lahan terbuka dengan paparan sinar matahari penuh.', 'img/general/Cabai Fatalii.png'),
('Benih Cabai Ghost Pepper', 'benih', 15000, '1 pack berisi ±12 biji <br> - Super Pedas <br> - Tingkat Pedas: ±1.041.427 SHU <br> - Asal: India Timur Laut <br> - Panen: ±100 hari', 'Benih Cabai Ghost Pepper atau Bhut Jolokia berasal dari Assam, India, dan pernah menyandang gelar cabai terpedas di dunia. Dengan tingkat pedas lebih dari 1 juta SHU, cabai ini memberikan sensasi pedas yang datang perlahan namun bertahan lama. Memiliki warna merah menyala dengan aroma khas buah tropis. Cocok untuk olahan saus super pedas dan sambal bubuk. Dapat tumbuh baik di iklim hangat dengan sinar matahari penuh.', 'img/general/Cabai Ghost Pepper.png'),
('Benih Cabai Habanero', 'benih', 10000, '1 pack berisi ±12 biji <br> - Pedas Buah Tropis <br> - Tingkat Pedas: 100.000–350.000 SHU <br> - Warna: Oranye/merah <br> - Panen: ±80 hari', 'Benih Cabai Habanero merupakan varietas populer dari Meksiko dan Karibia. Dikenal dengan rasa pedas tajam yang berpadu aroma buah tropis seperti mangga dan pepaya. Buahnya kecil dan berwarna oranye cerah saat matang, sangat cocok untuk saus pedas dan bumbu masakan. Tumbuh optimal pada suhu hangat dan membutuhkan penyiraman teratur dengan tanah berdrainase baik.', 'img/general/Cabai Habanero.png'),
('Benih Cabai Jalapeno', 'benih', 20000, '1 pack berisi ±12 biji <br> - Pedas Sedang <br> - Tingkat Pedas: 2.500–8.000 SHU <br> - Asal: Meksiko <br> - Panen: ±75 hari', 'Benih Cabai Jalapeno adalah varietas klasik asal Meksiko dengan rasa pedas sedang dan aroma segar. Cabai ini sering digunakan dalam pizza, taco, dan berbagai masakan internasional. Buahnya berwarna hijau tua dan berubah merah saat matang, berukuran sekitar 7–9 cm. Cocok untuk ditanam di pot atau kebun kecil dengan hasil panen melimpah dan perawatan mudah.', 'img/general/Cabai Jalapeno.png'),
('Benih Cabai Naga Viper', 'benih', 28000, '1 pack berisi ±12 biji <br> - Super Hibrida <br> - Tingkat Pedas: ±1.382.118 SHU <br> - Asal: Inggris <br> - Panen: ±95 hari', 'Benih Cabai Naga Viper merupakan hasil persilangan antara tiga varietas ekstrem: Naga Morich, Bhut Jolokia, dan Trinidad Scorpion. Dikenal karena tingkat kepedasannya yang luar biasa tinggi dengan sensasi pedas bertahap. Buahnya berwarna merah tua dengan tekstur keriput khas. Cocok untuk kolektor cabai langka atau penggemar cabai ekstrem. Tumbuh baik di iklim hangat dengan penyinaran penuh.', 'img/general/Cabai Naga Viper.png'),
('Benih Cabai Orange Drop', 'benih', 17000, '1 pack berisi ±12 biji <br> - Cabai Mini <br> - Warna Oranye Cerah <br> - Pedas Menyegarkan <br> - Panen: ±85 hari', 'Benih Cabai Orange Drop menghasilkan cabai mini berwarna oranye cerah yang menarik. Rasa pedasnya ringan hingga sedang dengan aroma segar khas cabai muda. Selain untuk konsumsi, varietas ini juga sering dijadikan tanaman hias karena tampilannya yang estetik dan produktif. Cocok untuk ditanam di pot hias di teras atau balkon.', 'img/general/Cabai Orange Drop.png'),
('Benih Cabai Scotch Bonnet', 'benih', 25000, '1 pack berisi ±12 biji <br> - Pedas Tropis <br> - Tingkat Pedas: 100.000–350.000 SHU <br> - Asal: Karibia <br> - Panen: ±90 hari', 'Benih Cabai Scotch Bonnet berasal dari Kepulauan Karibia dan sangat populer dalam masakan Jamaika. Cabai ini memiliki bentuk menyerupai topi (bonnet) dengan warna kuning hingga merah cerah saat matang. Rasa pedasnya tajam dengan aroma buah tropis seperti nanas dan mangga. Cocok untuk saus pedas, masakan panggang, dan sambal khas Karibia.', 'img/general/Cabai Scotch Bonnet.png'),
('Benih Cabai Thai Chili', 'benih', 15000, '1 pack berisi ±12 biji <br> - Pedas Tajam <br> - Tingkat Pedas: 50.000–100.000 SHU <br> - Ukuran Kecil <br> - Panen: ±75 hari', 'Benih Cabai Thai Chili (Prik Kee Noo) merupakan cabai khas Asia Tenggara dengan rasa pedas tajam dan aroma segar. Sering digunakan dalam kuliner Thailand dan Indonesia seperti tumisan, sambal, dan sup pedas. Ukurannya kecil namun sangat produktif. Dapat tumbuh baik di pot maupun lahan, tahan panas, dan mudah perawatannya.', 'img/general/Cabai Thai Chili.png'),
('Pupuk ZA', 'nutrisi', 30000, 'Sumber Nitrogen <br> - Non-Organik <br> - Merangsang Daun <br> - 1kg', 'Pupuk ZA (Zwavelzure Ammoniak) merupakan pupuk kimia yang mengandung Nitrogen (21%) dan Sulfur (24%). Berfungsi utama untuk mempercepat pertumbuhan daun dan batang pada fase vegetatif. Sangat baik digunakan pada tanaman sayuran daun, padi, dan tanaman hias. Sebaiknya digunakan dengan dosis terukur dan tidak berlebihan.', 'img/general/Pupuk X.png'),
('Sekam Bakar', 'media', 7000, 'Media Tanam <br> - Porositas Tinggi <br> - Steril <br> - 1 karung', 'Sekam bakar adalah hasil pembakaran sebagian kulit padi yang dijadikan media tanam dengan porositas tinggi. Mampu menjaga kelembapan dan sirkulasi udara di dalam tanah, serta membantu akar tanaman tumbuh lebih sehat. Sudah steril dari jamur dan hama, ideal untuk campuran tanah maupun media hidroponik.', 'img/general/Sekam Bakar.png'),
('Spons Hidroponik', 'media', 3000, 'Media Semai <br> - Hidroponik <br> - Menyerap Air <br> - 1 Papan', 'Spons khusus untuk penyemaian benih pada sistem hidroponik. Memiliki daya serap air tinggi namun tetap menjaga aerasi akar agar tidak tergenang. Cocok digunakan untuk semai sayuran daun seperti selada, bayam, dan kangkung. Dapat dipotong sesuai ukuran netpot atau tray semai.', 'img/general/Spons Hidroponik.png'),
('Gunting Tanaman', 'peralatan', 38000, 'Stainless Steel <br> - Tajam & Presisi <br> - Ergonomis <br> - Anti Karat', 'Gunting pangkas berkualitas tinggi berbahan stainless steel yang tahan lama dan tajam. Dirancang dengan gagang ergonomis agar nyaman di tangan, cocok untuk memangkas ranting kecil, daun, atau bunga. Ideal digunakan untuk tanaman hias maupun kebun sayur.', 'img/general/Gunting Tanaman.png'),
('Set Komplit Berkebun', 'promo', 75000, 'Peralatan Lengkap <br> - Termasuk Sekop, Sarung Tangan, dan Gunting <br> - Material Kuat <br> - Cocok untuk Pemula', 'Set komplit berkebun berisi perlengkapan dasar seperti sekop mini, sarung tangan, gunting tanaman, dan garpu tanah. Terbuat dari bahan berkualitas tinggi dan desain ergonomis untuk kenyamanan berkebun. Ideal bagi pemula yang ingin memulai berkebun di rumah atau kebun kecil.', 'img/general/Set Komplit.png');

-- =====================================================================================
-- SKRIP SEED UNTUK TABEL 'news'
-- =====================================================================================
-- Skrip ini mengisi tabel 'news' dengan data berita awal.

-- Kosongkan data yang ada untuk mencegah duplikasi
TRUNCATE TABLE public.news RESTART IDENTITY;

-- Masukkan data berita baru
INSERT INTO public.news (title, excerpt, image_url) VALUES
('5 Tips Jitu Memulai Hidroponik di Rumah', 'Hidroponik tidak sesulit yang dibayangkan. Dengan panduan ini, Anda bisa memulai kebun hidroponik mini di balkon atau halaman rumah Anda.', 'img/Pemula.png'),
('Mengenal Nutrisi A-B Mix: Kunci Sukses Tanaman Hidroponik', 'Apa itu nutrisi A-B Mix dan mengapa sangat penting? Pelajari cara meracik dan menggunakannya untuk hasil panen yang maksimal.', 'img/Nutrisi AB.png'),
('Perbandingan Media Tanam: Rockwool, Cocopeat, atau Hidroton?', 'Setiap media tanam memiliki kelebihan dan kekurangan. Kami bantu Anda memilih yang terbaik sesuai dengan jenis tanaman dan sistem Anda.', 'img/Cabai Silang.png');
