-- =====================================================================================
-- PERBAIKAN SKEMA PENTING (JALANKAN INI DI EDITOR SQL SUPABASE ANDA)
-- =====================================================================================
-- Perintah berikut akan memperbaiki relasi dan izin akses agar data pelanggan
-- muncul dengan benar di halaman admin.

-- PERINTAH 1: Tambahkan kebijakan RLS ke tabel 'profiles' agar admin bisa membacanya.
-- Ini adalah langkah yang paling mungkin hilang.
CREATE POLICY "Allow admin to read all profiles"
ON public.profiles
FOR SELECT
USING (is_admin());

-- PERINTAH 2: Hapus foreign key yang lama (jika belum dijalankan sebelumnya).
-- CATATAN: Nama constraint 'orders_user_id_fkey' mungkin berbeda di database Anda.
-- Jika perintah ini gagal, cari nama yang benar di dasbor Supabase Anda.
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_user_id_fkey;

-- PERINTAH 3: Tambahkan foreign key baru yang menunjuk ke public.profiles(id).
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id);

-- =====================================================================================
-- SKEMA LENGKAP (UNTUK REFERENSI)
-- =====================================================================================

-- Skema ini mendefinisikan tabel dan kebijakan keamanan untuk sistem pesanan.

-- Tabel 'profiles'
-- Pastikan RLS diaktifkan pada tabel ini
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Kebijakan untuk 'profiles': Pengguna bisa melihat dan mengedit profil mereka sendiri
CREATE POLICY "Allow users to access their own profile"
ON public.profiles
FOR ALL
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Kebijakan BARU untuk 'profiles': Admin bisa melihat semua profil
CREATE POLICY "Allow admin to read all profiles"
ON public.profiles
FOR SELECT
USING (is_admin());


-- Tabel 'orders'
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    order_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_details JSONB NOT NULL,
    shipping_address JSONB NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Proses Admin'::text NOT NULL,
    shipping_receipt TEXT,
    notes TEXT
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view their own orders"
ON public.orders FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow users to create their own orders"
ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);


-- Infrastruktur Admin
CREATE TABLE IF NOT EXISTS public.admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id)
);

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Kebijakan Admin untuk 'orders'
CREATE POLICY "Allow admin full access" ON public.orders
FOR ALL USING (is_admin()) WITH CHECK (is_admin());


-- Supabase Realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
  END IF;
END $$;
